version: '3'

services:
  mongo:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    volumes:
      - ./data/mongo:/data/db
    labels:
      nl.demeyerthom.environment: testing
    networks:
      - testing

networks:
  testing:
